### ISSUE TITLE
Error appears when using gsea in ebrowser

### ISSUE THREAD

**Issue by olkap** [lgeistlinger/EnrichmentBrowser#7]
Hi,
I would like to analyse my microarray data with EnrichmentBrowser using multiple methods and multiple gene sets. When I run ebrowser function with gsea method, I get the following error:
```
Error in `[[<-`(`*tmp*`, name, value = c(`79501` = 0.06, `729759` = 0.22,  : 
  7195 elements in value to replace 23989 elements
```

Can you please tell me how to solve this problem?

Below I include the sample code, in which the similar error is reproduced on ALL data:

```
#_________________
# Load packages
library("EnrichmentBrowser")
library("ALL")
library("hgu95av2.db")

#________________
# Load the ALL dataset

data(ALL)

#select B-cell ALL patients with and without the BCR/ABL fusion
ind.bs <- grep("^B", ALL$BT)  
ind.mut <- which(ALL$mol.biol %in% c("BCR/ABL", "NEG"))
sset <- intersect(ind.bs, ind.mut)
all.eset <- ALL[, sset]

#We compute gene expression values as the average of the corresponding probe values.
allSE <- probe2gene(all.eset) 

#______________________
# Create GROUP variable (the GROUP variable indicates whether the BCR-ABL gene fusion is present (1) or not (0).)
allSE$GROUP <- ifelse(allSE$mol.biol == "BCR/ABL", 1, 0)

#_____________________
# Gene sets
kegg.gs <- getGenesets(org="hsa", db="kegg")

#____________________
#ORA analysis - it works

ebrowser( 
  meth=c("ora"),
  exprs = allSE, 
  org="hsa", 
  data.type = "ma",
  norm.method = "none",
  gs=kegg.gs, 
  comb=TRUE, 
  nr.show=3)

#____________________
# GSEA analysis - it throws an error

ebrowser( 
  meth=c("gsea"),
  exprs = allSE, 
  org="hsa", 
  data.type = "ma",
  norm.method = "none",
  gs=kegg.gs, 
  comb=TRUE, 
  nr.show=3)
```

Below, I include the messages that appear after running the last line of the code:
```
DE analysis ...
Execute GSEA ...
Permutations: 1 -- 100
Permutations: 101 -- 200
Permutations: 201 -- 300
Permutations: 301 -- 400
Permutations: 401 -- 500
Permutations: 501 -- 600
Permutations: 601 -- 700
Permutations: 701 -- 800
Permutations: 801 -- 900
Permutations: 901 -- 1000
Processing ...
Creating gene report ...
Creating set view ...
Creating kegg view ...
Info: Downloading xml files for hsa05146, 1/1 pathways..
Info: Downloading png files for hsa05146, 1/1 pathways..
'select()' returned 1:1 mapping between keys and columns
Info: Working in directory C:/workshop
Info: Writing image file hsa05146.kpath.png
Info: Downloading xml files for hsa05330, 1/1 pathways..
Info: Downloading png files for hsa05330, 1/1 pathways..
'select()' returned 1:1 mapping between keys and columns
Info: Working in directory C:/workshop
Info: Writing image file hsa05330.kpath.png
Info: Downloading xml files for hsa05416, 1/1 pathways..
Info: Downloading png files for hsa05416, 1/1 pathways..
'select()' returned 1:1 mapping between keys and columns
Info: Working in directory C:/workshop
Info: Writing image file hsa05416.kpath.png
Error in `[[<-`(`*tmp*`, name, value = c(`5595` = 0.01, `1557` = -0.02,  : 
  4695 elements in value to replace 9010 elements
```

The results of sessionInfo():
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] pathview_1.20.0             bindrcpp_0.2.2              hgu95av2.db_3.2.3           org.Hs.eg.db_3.6.0         
 [5] AnnotationDbi_1.42.1        ALL_1.22.0                  EnrichmentBrowser_2.10.5    graph_1.58.0               
 [9] SummarizedExperiment_1.10.1 DelayedArray_0.6.2          BiocParallel_1.14.2         matrixStats_0.54.0         
[13] Biobase_2.40.0              GenomicRanges_1.32.6        GenomeInfoDb_1.16.0         IRanges_2.14.10            
[17] S4Vectors_0.18.3            BiocGenerics_0.26.0        

loaded via a namespace (and not attached):
  [1] backports_1.1.2          GOstats_2.46.0           circlize_0.4.4           Hmisc_4.1-1              BiocFileCache_1.4.0     
  [6] plyr_1.8.4               lazyeval_0.2.1           GSEABase_1.42.0          splines_3.5.1            ggplot2_3.0.0           
 [11] digest_0.6.15            BiocInstaller_1.30.0     ensembldb_2.4.1          htmltools_0.3.6          GO.db_3.6.0             
 [16] magrittr_1.5             checkmate_1.8.5          memoise_1.1.0            BSgenome_1.48.0          cluster_2.0.7-1         
 [21] limma_3.36.2             ComplexHeatmap_1.18.1    Biostrings_2.48.0        annotate_1.58.0          R.utils_2.6.0           
 [26] ggbio_1.28.4             prettyunits_1.0.2        colorspace_1.3-2         blob_1.1.1               rappdirs_0.3.1          
 [31] dplyr_0.7.6              crayon_1.3.4             RCurl_1.95-4.11          genefilter_1.62.0        bindr_0.1.1             
 [36] survival_2.42-6          VariantAnnotation_1.26.1 glue_1.3.0               gtable_0.2.0             zlibbioc_1.26.0         
 [41] XVector_0.20.0           GetoptLong_0.1.7         Rgraphviz_2.24.0         shape_1.4.4              SparseM_1.77            
 [46] scales_0.5.0             DBI_1.0.0                GGally_1.4.0             edgeR_3.22.3             Rcpp_0.12.18            
 [51] xtable_1.8-2             progress_1.2.0           htmlTable_1.12           foreign_0.8-71           bit_1.1-14              
 [56] OrganismDbi_1.22.0       Formula_1.2-3            AnnotationForge_1.22.1   htmlwidgets_1.2          httr_1.3.1              
 [61] RColorBrewer_1.1-2       acepack_1.4.1            pkgconfig_2.0.1          reshape_0.8.7            XML_3.98-1.12           
 [66] R.methodsS3_1.7.1        nnet_7.3-12              dbplyr_1.2.2             locfit_1.5-9.1           tidyselect_0.2.4        
 [71] rlang_0.2.1              reshape2_1.4.3           munsell_0.5.0            tools_3.5.1              RSQLite_2.1.1           
 [76] stringr_1.3.1            knitr_1.20               bit64_0.9-7              purrr_0.2.5              KEGGREST_1.20.1         
 [81] AnnotationFilter_1.4.0   RBGL_1.56.0              R.oo_1.22.0              KEGGgraph_1.40.0         biomaRt_2.36.1          
 [86] compiler_3.5.1           rstudioapi_0.7           curl_3.2                 png_0.1-7                PFAM.db_3.6.0           
 [91] tibble_1.4.2             geneplotter_1.58.0       stringi_1.1.7            GenomicFeatures_1.32.0   lattice_0.20-35         
 [96] ProtGenerics_1.12.0      Matrix_1.2-14            pillar_1.3.0             GlobalOptions_0.1.0      data.table_1.11.4       
[101] bitops_1.0-6             rtracklayer_1.40.3       R6_2.2.2                 latticeExtra_0.6-28      hwriter_1.3.2           
[106] gridExtra_2.3            biocGraph_1.42.0         dichromat_2.0-0          assertthat_0.2.0         DESeq2_1.20.0           
[111] Category_2.46.0          rjson_0.2.20             ReportingTools_2.20.0    safe_3.20.0              GenomicAlignments_1.16.0
[116] Rsamtools_1.32.2         GenomeInfoDbData_1.1.0   hms_0.4.2                grid_3.5.1               rpart_4.1-13            
[121] biovizBase_1.28.1        base64enc_0.1-3       
```

**Comment by lgeistlinger** [comment]
Thanks a lot for reporting this.
This is fixed in the new release version EnrichmentBrowser v2.10.6 that will become available (typically within 24 hours) under: 

http://bioconductor.org/packages/EnrichmentBrowser

**Comment by olkap** [comment]
Hi,
I installed the new version of EnrichmentBrowser and I still get an error:

```
> ebrowser( 
+   meth=c("gsea"),
+   exprs = allSE, 
+   org="hsa", 
+   data.type = "ma",
+   norm.method = "none",
+   gs=kegg.gs, 
+   grn=kegg.grn, 
+   comb=TRUE, 
+   nr.show=3)
DE analysis ...
Execute GSEA ...
Permutations: 1 -- 100
Permutations: 101 -- 200
Permutations: 201 -- 300
Permutations: 301 -- 400
Permutations: 401 -- 500
Permutations: 501 -- 600
Permutations: 601 -- 700
Permutations: 701 -- 800
Permutations: 801 -- 900
Permutations: 901 -- 1000
Processing ...
Creating gene report ...
Creating set view ...
Creating kegg view ...
Info: Downloading xml files for hsa05146, 1/1 pathways..
Info: Downloading png files for hsa05146, 1/1 pathways..
'select()' returned 1:1 mapping between keys and columns
Info: Working in directory C:/workshop
Info: Writing image file hsa05146.kpath.png
Info: Downloading xml files for hsa05330, 1/1 pathways..
Info: Downloading png files for hsa05330, 1/1 pathways..
'select()' returned 1:1 mapping between keys and columns
Info: Working in directory C:/workshop
Info: Writing image file hsa05330.kpath.png
Info: Downloading xml files for hsa05416, 1/1 pathways..
Info: Downloading png files for hsa05416, 1/1 pathways..
'select()' returned 1:1 mapping between keys and columns
Info: Working in directory C:/workshop
Info: Writing image file hsa05416.kpath.png
Creating graph view ...
Error in V_recycle(value, x, x_what = "value", skeleton_what = "x") : 
  'NROW(value)' is greater than 'length(x)'
```
sessionInfo():
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] pathview_1.20.0             bindrcpp_0.2.2              hgu95av2.db_3.2.3           org.Hs.eg.db_3.6.0         
 [5] AnnotationDbi_1.42.1        ALL_1.22.0                  EnrichmentBrowser_2.10.6    graph_1.58.0               
 [9] SummarizedExperiment_1.10.1 DelayedArray_0.6.4          BiocParallel_1.14.2         matrixStats_0.54.0         
[13] Biobase_2.40.0              GenomicRanges_1.32.6        GenomeInfoDb_1.16.0         IRanges_2.14.10            
[17] S4Vectors_0.18.3            BiocGenerics_0.26.0        

loaded via a namespace (and not attached):
  [1] backports_1.1.2          GOstats_2.46.0           circlize_0.4.4           Hmisc_4.1-1             
  [5] BiocFileCache_1.4.0      plyr_1.8.4               lazyeval_0.2.1           GSEABase_1.42.0         
  [9] splines_3.5.1            ggplot2_3.0.0            digest_0.6.15            BiocInstaller_1.30.0    
 [13] ensembldb_2.4.1          htmltools_0.3.6          GO.db_3.6.0              magrittr_1.5            
 [17] checkmate_1.8.5          memoise_1.1.0            BSgenome_1.48.0          cluster_2.0.7-1         
 [21] limma_3.36.2             ComplexHeatmap_1.18.1    Biostrings_2.48.0        annotate_1.58.0         
 [25] R.utils_2.6.0            ggbio_1.28.4             prettyunits_1.0.2        colorspace_1.3-2        
 [29] blob_1.1.1               rappdirs_0.3.1           dplyr_0.7.6              crayon_1.3.4            
 [33] RCurl_1.95-4.11          genefilter_1.62.0        bindr_0.1.1              survival_2.42-6         
 [37] VariantAnnotation_1.26.1 glue_1.3.0               gtable_0.2.0             zlibbioc_1.26.0         
 [41] XVector_0.20.0           GetoptLong_0.1.7         graphite_1.26.1          Rgraphviz_2.24.0        
 [45] shape_1.4.4              SparseM_1.77             scales_0.5.0             DBI_1.0.0               
 [49] GGally_1.4.0             edgeR_3.22.3             Rcpp_0.12.18             xtable_1.8-2            
 [53] progress_1.2.0           htmlTable_1.12           foreign_0.8-71           bit_1.1-14              
 [57] OrganismDbi_1.22.0       Formula_1.2-3            AnnotationForge_1.22.2   htmlwidgets_1.2         
 [61] httr_1.3.1               RColorBrewer_1.1-2       acepack_1.4.1            pkgconfig_2.0.1         
 [65] reshape_0.8.7            XML_3.98-1.13            R.methodsS3_1.7.1        nnet_7.3-12             
 [69] dbplyr_1.2.2             locfit_1.5-9.1           tidyselect_0.2.4         rlang_0.2.1             
 [73] reshape2_1.4.3           munsell_0.5.0            tools_3.5.1              RSQLite_2.1.1           
 [77] stringr_1.3.1            knitr_1.20               bit64_0.9-7              purrr_0.2.5             
 [81] KEGGREST_1.20.1          AnnotationFilter_1.4.0   RBGL_1.56.0              R.oo_1.22.0             
 [85] KEGGgraph_1.40.0         biomaRt_2.36.1           compiler_3.5.1           rstudioapi_0.7          
 [89] curl_3.2                 png_0.1-7                PFAM.db_3.6.0            tibble_1.4.2            
 [93] geneplotter_1.58.0       stringi_1.1.7            GenomicFeatures_1.32.0   lattice_0.20-35         
 [97] ProtGenerics_1.12.0      Matrix_1.2-14            pillar_1.3.0             GlobalOptions_0.1.0     
[101] data.table_1.11.4        bitops_1.0-6             rtracklayer_1.40.3       R6_2.2.2                
[105] latticeExtra_0.6-28      hwriter_1.3.2            gridExtra_2.3            biocGraph_1.42.0        
[109] dichromat_2.0-0          assertthat_0.2.0         DESeq2_1.20.0            Category_2.46.0         
[113] rjson_0.2.20             ReportingTools_2.20.0    safe_3.20.0              GenomicAlignments_1.16.0
[117] Rsamtools_1.32.2         GenomeInfoDbData_1.1.0   hms_0.4.2                grid_3.5.1              
[121] rpart_4.1-13             biovizBase_1.28.1        base64enc_0.1-3         
```

**Comment by lgeistlinger** [comment]
EDIT: apologies @olkap - I actually _can_ reproduce the error and I'm currently looking into it.
I used the devel version of the packages beforehand, when I couldn't reproduce the error.

**Comment by lgeistlinger** [comment]
Alright, this is now fixed in the new release version EnrichmentBrowser v2.10.7 that will become available (typically within 24 hours) under:

http://bioconductor.org/packages/EnrichmentBrowser

Apologies for the inconvenience!

**Comment by olkap** [comment]
Now it works. Thank you.
